//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.20 at 07:06:56 PM IST 
//


package com.kasun.corebankdummy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountNoSend" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="accountNoReceive" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="transferAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountNoSend",
    "accountNoReceive",
    "transferAmount"
})
@XmlRootElement(name = "fundTransferOtherRequest")
public class FundTransferOtherRequest {

    protected int accountNoSend;
    protected int accountNoReceive;
    protected double transferAmount;

    /**
     * Gets the value of the accountNoSend property.
     * 
     */
    public int getAccountNoSend() {
        return accountNoSend;
    }

    /**
     * Sets the value of the accountNoSend property.
     * 
     */
    public void setAccountNoSend(int value) {
        this.accountNoSend = value;
    }

    /**
     * Gets the value of the accountNoReceive property.
     * 
     */
    public int getAccountNoReceive() {
        return accountNoReceive;
    }

    /**
     * Sets the value of the accountNoReceive property.
     * 
     */
    public void setAccountNoReceive(int value) {
        this.accountNoReceive = value;
    }

    /**
     * Gets the value of the transferAmount property.
     * 
     */
    public double getTransferAmount() {
        return transferAmount;
    }

    /**
     * Sets the value of the transferAmount property.
     * 
     */
    public void setTransferAmount(double value) {
        this.transferAmount = value;
    }

}
