//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.20 at 07:06:56 PM IST 
//


package com.kasun.corebankdummy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountSend" type="{http://kasun.com/corebankdummy}account"/>
 *         &lt;element name="accountReceive" type="{http://kasun.com/corebankdummy}account"/>
 *         &lt;element name="transferredAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountSend",
    "accountReceive",
    "transferredAmount",
    "error"
})
@XmlRootElement(name = "fundTransferOtherResponse")
public class FundTransferOtherResponse {

    @XmlElement(required = true)
    protected Account accountSend;
    @XmlElement(required = true)
    protected Account accountReceive;
    protected double transferredAmount;
    @XmlElement(required = true)
    protected String error;

    /**
     * Gets the value of the accountSend property.
     * 
     * @return
     *     possible object is
     *     {@link Account }
     *     
     */
    public Account getAccountSend() {
        return accountSend;
    }

    /**
     * Sets the value of the accountSend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account }
     *     
     */
    public void setAccountSend(Account value) {
        this.accountSend = value;
    }

    /**
     * Gets the value of the accountReceive property.
     * 
     * @return
     *     possible object is
     *     {@link Account }
     *     
     */
    public Account getAccountReceive() {
        return accountReceive;
    }

    /**
     * Sets the value of the accountReceive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account }
     *     
     */
    public void setAccountReceive(Account value) {
        this.accountReceive = value;
    }

    /**
     * Gets the value of the transferredAmount property.
     * 
     */
    public double getTransferredAmount() {
        return transferredAmount;
    }

    /**
     * Sets the value of the transferredAmount property.
     * 
     */
    public void setTransferredAmount(double value) {
        this.transferredAmount = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

}
