//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.20 at 07:06:56 PM IST 
//


package com.kasun.corebankdummy;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kasun.corebankdummy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kasun.corebankdummy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FundTransferOwnResponse }
     * 
     */
    public FundTransferOwnResponse createFundTransferOwnResponse() {
        return new FundTransferOwnResponse();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link GetAccountBalanceResponse }
     * 
     */
    public GetAccountBalanceResponse createGetAccountBalanceResponse() {
        return new GetAccountBalanceResponse();
    }

    /**
     * Create an instance of {@link GetAccountBalanceRequest }
     * 
     */
    public GetAccountBalanceRequest createGetAccountBalanceRequest() {
        return new GetAccountBalanceRequest();
    }

    /**
     * Create an instance of {@link GetTotalAccountBalanceRequest }
     * 
     */
    public GetTotalAccountBalanceRequest createGetTotalAccountBalanceRequest() {
        return new GetTotalAccountBalanceRequest();
    }

    /**
     * Create an instance of {@link FundTransferOwnRequest }
     * 
     */
    public FundTransferOwnRequest createFundTransferOwnRequest() {
        return new FundTransferOwnRequest();
    }

    /**
     * Create an instance of {@link GetAccountRequest }
     * 
     */
    public GetAccountRequest createGetAccountRequest() {
        return new GetAccountRequest();
    }

    /**
     * Create an instance of {@link GetAccountResponse }
     * 
     */
    public GetAccountResponse createGetAccountResponse() {
        return new GetAccountResponse();
    }

    /**
     * Create an instance of {@link GetTotalAccountBalanceResponse }
     * 
     */
    public GetTotalAccountBalanceResponse createGetTotalAccountBalanceResponse() {
        return new GetTotalAccountBalanceResponse();
    }

    /**
     * Create an instance of {@link FundTransferOtherRequest }
     * 
     */
    public FundTransferOtherRequest createFundTransferOtherRequest() {
        return new FundTransferOtherRequest();
    }

    /**
     * Create an instance of {@link FundTransferOtherResponse }
     * 
     */
    public FundTransferOtherResponse createFundTransferOtherResponse() {
        return new FundTransferOtherResponse();
    }

}
